language: python

python:
    - 3.8

before_install:
  - python --version
  - sudo mkdir /etc/slurm-llnl
  - sudo cp slurm.conf /etc/slurm-llnl
#  - cp batchtools.conf.R tests/testthat
#  - sudo /etc/init.d/slurmctld restart
#  - sudo /etc/init.d/slurmd restart
  - sudo apt-get install -y slurm-llnl
  - sudo pip install requests
#  - sudo /usr/sbin/create-munge-key
  - sudo service munge start
  - cd jbrowse
