# see https://github.com/tdhock/PeakSegPipeline/blob/master/.travis.yml

language: python
python:
  - "2.7"

script:  echo "Hello world"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  slack: capstoneteam2019-2020:bvR3ofKEeSgoYiI9E4pchZs6
