language: python

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - sudo apt install libdb5.3-dev
  - sudo apt install slurm-llnl
  # Setup slurm.conf for testing
  - sudo cp slurm.conf /etc/slurm-llnl
  - sudo service munge start
  - sudo /etc/init.d/slurmctld restart
  - sudo /etc/init.d/slurmd restart
  - sinfo
  # Setup python dependencies
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install requests
  - pip install pybbi
  - pip install pandas
  - pip install numpy
  - pip install bsddb3
  - pip install git+https://github.com/deltarod/PeakError.git
  - pip install codecov

script:
  - pytest tests/

after_success:
  - codecov



